### ISSUE TITLE
How to deploy the app into cumulocity?

### ISSUE THREAD

**Issue by pranay-91** [dwiyatci/cumulocity-smart-apps-webpack#1]
I would like to deploy this app as an application into cumulocity.
I have tried the following steps:
- Did `yarn build` to generate bundled files into assets folder
- I zipped the asset folder and uploaded the zip file via Add application option in Cumulocity
- I get Nginx error 404 cannot be found.

Would anyone be able to provide information step by step on how to deploy this app?

Thanks

**Comment by dwiyatci** [comment]
Hi, @pranay-91! :)

I think I made a bit mistake in setting the `publicPath` in the `output` section of the webpack configuration. I have fixed that and have also updated the docs, explaining how to deploy the app to Cumulocity in particular. Let me know if this solves your issue.

**Comment by pranay-91** [comment]
Hi @dwiyatci,
Thanks for updated docs and the fixes.
I have followed the steps. unfortunately I am getting same error 404 on nginx.
It might possibly to do with the tenancy. 

Do we need to provide cumulocity.json or App manifest file inside the zip file?
Have you tested this boilerplate with any cumulocity tenancy?

I am using mac os high sierra.
The cumulocity version i am using is 8.19.19 backend and 8.19.18 ui.

Thanks

**Comment by pranay-91** [comment]
Hi @dwiyatci,
I have resolved the issue.
The zip (assets) needs to include only the relevant file not including the root directory itself.
For e.g. If we have assets bundled folder
- assets
   - file A
   - file B

The zip should be(if we renamed the assets to smart-apps)
- smart-apps.zip
  - file A
  - file B

Following would not work:
- smart-apps.zip
  - smart-apps
     - file A
     - file B

Thanks

**Comment by dwiyatci** [comment]
@pranay-91 Glad that you resolved the issue. Yes, I guess I've already mentioned it quite clearly in the [updated docs](https://github.com/dwiyatci/cumulocity-smart-apps-webpack#deploying-to-a-cumulocity-tenant).

> Zip all files under assets directory (**⚠️ not the directory itself!**) and name the ZIP file as "smartapps" or whatever you want to call the app.

Cheers, mate! ;)
