### ISSUE TITLE
404 error 

### ISSUE THREAD

**Issue by babupca** [dwiyatci/cumulocity-smart-apps-webpack#2]
Hi, 
I have build the application and deployed it in the adamos. When i click the application i go to the 404 page.

As per your steps in the github, i zipped the assets contents inside to another folder named "smartapps", but it seems not working.

If i'm correct, whenever i click the smartapps application, it should take me to that angular app, but instead it is saying 404 error.

Could you please let me know, what wrong i'm doing here.

https://tempar.adamos.com/apps/smartapps/index.html

**Comment by dwiyatci** [comment]
> As per your steps in the github, i zipped the assets contents inside to another folder named "smartapps", but it seems not working.

Don't zip your "smartapps" folder, zip the contents without any enclosing folder. To make sure you do it right: after you zip the contents to a ZIP archive, e.g. "smartapps.zip", try to "Extract Here" that ZIP archive and check whether `index.html` file is extracted directly to the current location of the archive.

**Comment by babupca** [comment]
Current location means, which place you are talking about? is the below location with in the cumulocity-smart-apps-webpack
![image](https://user-images.githubusercontent.com/2504343/43522224-5256f260-95b6-11e8-865d-3fb4d1df4cea.png)
---------------------------------------
![image](https://user-images.githubusercontent.com/2504343/43522001-89ee9de6-95b5-11e8-9a59-312462952c07.png)
![image](https://user-images.githubusercontent.com/2504343/43522052-b35b02b4-95b5-11e8-81a1-6899ac932159.png)
![image](https://user-images.githubusercontent.com/2504343/43522095-e2ed1a1c-95b5-11e8-9957-1611302a67a1.png)

### This smartapps, is zipped and uploaded to the cumulocity, is this correct ?

![image](https://user-images.githubusercontent.com/2504343/43522116-f9e3e9d0-95b5-11e8-94a7-e4750441dd7a.png)

**Comment by babupca** [comment]
I basically extracted all the contents of the assets to the "cumulocity-smart-apps-webpack" folder. Is this correct. 

And then i uploaded the zipped this and uploaded to the cumulocity, but still i get 404 error only

**Comment by dwiyatci** [comment]
Please refer to [this comment](https://github.com/dwiyatci/cumulocity-smart-apps-webpack/issues/1#issuecomment-390651411) in issue #1.

**Comment by babupca** [comment]
@dwiyatci , Thank you very much, its working now. I did not recognize that another folder is getting added inside the zip folder, this is causing the issue basically. 

Thanks for responding quickly
